spring:
  application:
    name: Api-Rest
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: "jdbc:h2:mem:Api-Rest;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.H2Dialect
    defer-datasource.initializacion: true
    hibernate:
      ddl-auto: create-drop

